name: 'Napptive Playground action'
author: 'Napptive'
description: 'Execute Napptive Playground commands. The Playground offers a managed service to deploy complex cloud-native applications.'
inputs:
  debug:
    description: 'Debug flag in commands'
    required: false
    default: false
  cmd:
    description: 'Command to execute'
    required: true
  environment:
    description: 'To specify a target account/environment'
    required: false
  playgroundConfigFile:
    description: 'To use a custom YAML file to change the target playground installation'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.debug }}
    - ${{ inputs.cmd }}
    - ${{ inputs.environment }}
    - ${{ inputs.playgroundConfigFile }}
branding:
  icon: 'play'  
  color: 'blue'
